### ISSUE TITLE
Parse file from memory

### ISSUE THREAD

**Issue by perseus-me** [eliben/gosax#1]
Is the way to parse file from Reader or byte slice? I want parse xml file from zip archive (xlsx), but I don't want to create temporary file on file system.

**Comment by MatthiasLohr** [comment]
@eliben, any thought on this?

**Comment by MatthiasLohr** [comment]
I found a fork which provides this functionality: https://github.com/thefish/gosax.

**Comment by eliben** [comment]
If @thefish or anyone else is willing to contribute a PR for this, I'll gladly review

**Comment by thefish** [comment]
Hey @eliben , here is the PR
https://github.com/eliben/gosax/pull/2

**Comment by eliben** [comment]
#2 landed, so this is fixed. Thanks @thefish for the PR
